# Spring boot application
spring:
  application:
    name: dubbo-provider-demo

# Service version
demo:
  service:
    version: 1.0.0

# Base packages to scan Dubbo Components (e.g @Service , @Reference)
dubbo:
  scan:
    base-packages: com.forever.apache.service
  #提供方应用名称,用于计算依赖关系
  application:
    id: dubbo-provider-demo
    name: dubbo-provider-demo
  #使用dubbo协议,在12345端口暴露服务
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
  #使用zookeeper注册中心暴露服务地址
  registry:
    id: my-registry
    address: zookeeper://127.0.0.1:2181
    #address: N/A
